#!/usr/bin/env bash
set -euo pipefail

# shellcheck disable=SC1091
source "$(cd "$(dirname "$0")" && pwd)/core.sh"

AELAB_LOG_PREFIX="render"
load_host_env

AELAB_ROOT="${AELAB_ROOT:-$(aelab_root)}"

brewfile_path() {
  printf '%s/infra/generated/Brewfile' "$(repo_root)"
}

caddyfile_path() {
  printf '%s/infra/generated/Caddyfile' "$(repo_root)"
}

index_template_path() {
  printf '%s/infra/core/index.html' "$(repo_root)"
}

generated_web_root() {
  printf '%s/infra/generated' "$(repo_root)"
}

generated_web_root_relative() {
  printf '%s' "./generated"
}

generated_index_path() {
  printf '%s/index.html' "$(generated_web_root)"
}

append_unique() {
  local value="$1"
  local existing

  [[ -n "$value" ]] || return 0

  for existing in "${BREW_PACKAGES[@]:-}"; do
    [[ "$existing" != "$value" ]] || return 0
  done

  BREW_PACKAGES+=("$value")
}

append_unique_tap() {
  local value="$1"
  local existing

  [[ -n "$value" ]] || return 0

  for existing in "${BREW_TAPS[@]:-}"; do
    [[ "$existing" != "$value" ]] || return 0
  done

  BREW_TAPS+=("$value")
}

append_unique_cask() {
  local value="$1"
  local existing

  [[ -n "$value" ]] || return 0

  for existing in "${BREW_CASKS[@]:-}"; do
    [[ "$existing" != "$value" ]] || return 0
  done

  BREW_CASKS+=("$value")
}

append_list() {
  local raw="$1"
  local item

  raw="$(trim_commas "$raw")"
  [[ -n "$raw" ]] || return 0
  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    append_unique "$item"
  done
}

append_tap_list() {
  local raw="$1"
  local item

  raw="$(trim_commas "$raw")"
  [[ -n "$raw" ]] || return 0
  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    append_unique_tap "$item"
  done
}

append_cask_list() {
  local raw="$1"
  local item

  raw="$(trim_commas "$raw")"
  [[ -n "$raw" ]] || return 0
  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    append_unique_cask "$item"
  done
}

collect_service_packages() {
  local service_id
  local packages
  local casks

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    case "${AELAB_SERVICE_INSTALL_OPTIONAL:-}" in
      1|true|yes|on)
        continue
        ;;
    esac
    append_tap_list "${AELAB_SERVICE_BREW_TAPS:-}"
    packages="${AELAB_SERVICE_BREW_PACKAGES:-}"
    casks="${AELAB_SERVICE_BREW_CASKS:-}"
    if is_macos && is_arm64; then
      packages="${AELAB_SERVICE_BREW_PACKAGES_MACOS_ARM64:-$packages}"
      casks="${AELAB_SERVICE_BREW_CASKS_MACOS_ARM64:-$casks}"
    fi
    append_list "$packages"
    append_cask_list "$casks"
  done < <(requested_service_ids_with_groups_from_env)
}

collect_agent_packages() {
  local agent_id
  local kind
  local packages
  local casks

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    kind="$(known_agent_kind_for_id "$agent_id")" || continue
    load_agent_kind_definition "$kind"
    append_tap_list "${AELAB_AGENT_BREW_TAPS:-}"
    packages="${AELAB_AGENT_BREW_PACKAGES:-}"
    casks="${AELAB_AGENT_BREW_CASKS:-}"
    if is_macos && is_arm64; then
      packages="${AELAB_AGENT_BREW_PACKAGES_MACOS_ARM64:-$packages}"
      casks="${AELAB_AGENT_BREW_CASKS_MACOS_ARM64:-$casks}"
    fi
    append_list "$packages"
    append_cask_list "$casks"
  done < <(requested_agent_ids_from_env)
}

render_brewfile() {
  local tap
  local pkg
  local cask

  printf '# Generated by infra/commands/render.sh brew. Do not edit manually.\n'
  printf '# Based on config/host.toml, config/repo.toml, config/agents.toml, and config/services.toml.\n'
  printf '\n'

  if [[ -n "${BREW_TAPS[*]-}" ]]; then
    for tap in "${BREW_TAPS[@]}"; do
      printf 'tap "%s"\n' "$tap"
    done
    printf '\n'
  fi

  if [[ -n "${BREW_PACKAGES[*]-}" ]]; then
    for pkg in "${BREW_PACKAGES[@]}"; do
      printf 'brew "%s"\n' "$pkg"
    done
  fi

  if [[ -n "${BREW_CASKS[*]-}" ]]; then
    printf '\n'
    for cask in "${BREW_CASKS[@]}"; do
      printf 'cask "%s"\n' "$cask"
    done
  fi
}

overwrite_file_preserving_metadata() {
  local src="$1"
  local dest="$2"

  if [[ -e "$dest" ]]; then
    cat "$src" > "$dest"
    rm -f "$src"
  else
    mv "$src" "$dest"
  fi
}

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

display_timezone() {
  printf '%s' "${AELAB_DISPLAY_TIMEZONE:-Europe/Belgrade}"
}

normalize_host_alias() {
  local item="$1"
  item="${item#http://}"
  item="${item#https://}"
  item="${item%%/*}"
  item="${item%%.*}"
  item="$(lowercase "$item")"

  case "$item" in
    agents) printf '%s' "agent-server" ;;
    apps) printf '%s' "app-server" ;;
    data) printf '%s' "data-server" ;;
    *) printf '%s' "$item" ;;
  esac
}

host_url_for_current_host() {
  [[ -n "${AELAB_HOST:-}" ]] || return 0
  repo_cfg_value "hosts" "$AELAB_HOST"
}

caddy_tls_mode() {
  lowercase "${AELAB_CADDY_TLS:-off}"
}

caddy_site_host() {
  local url
  url="$(host_url_for_current_host)"
  [[ -n "$url" ]] || return 0
  url="${url#http://}"
  url="${url#https://}"
  url="${url%%/*}"
  printf '%s' "$url"
}

display_host_name() {
  scutil --get LocalHostName 2>/dev/null || hostname -s 2>/dev/null || hostname
}

tailscale_section_name() {
  local selected
  selected="${AELAB_HOST:-${TAILSCALE_DNS_NAME:-$(hostname -s 2>/dev/null || hostname)}}"
  normalize_host_alias "$selected"
}

tailscale_nav_entries() {
  repo_cfg_entries "hosts"
}

html_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  printf '%s' "$value"
}

js_single_quote_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//$'\n'/\\n}"
  value="${value//\'/\\\'}"
  printf '%s' "$value"
}

url_encode_path_segment() {
  local value="$1"
  local length="${#value}"
  local index
  local char
  local encoded=""

  for ((index = 0; index < length; index++)); do
    char="${value:index:1}"
    case "$char" in
      [a-zA-Z0-9._~-])
        encoded+="$char"
        ;;
      *)
        printf -v char '%%%02X' "'$char"
        encoded+="$char"
        ;;
    esac
  done

  printf '%s' "$encoded"
}

render_tailscale_nav_html() {
  local current="$1"
  local alias
  local url
  local class_name
  local label

  while IFS=$'\t' read -r alias url; do
    [[ -n "$alias" && -n "$url" ]] || continue
    class_name="segmented-link"
    label="$(normalize_host_alias "$alias")"
    if [[ "$label" == "$current" ]]; then
      class_name="segmented-link is-active"
    fi
    printf '        <a class="%s" href="%s" data-host-shortcut>%s</a>\n' \
      "$(html_escape "$class_name")" \
      "$(html_escape "$url")" \
      "$(html_escape "$label")"
  done < <(tailscale_nav_entries)
}

render_commit_hash() {
  git -C "$(repo_root)" rev-parse --short HEAD 2>/dev/null || printf '%s' "unknown"
}

agent_gateway_port() {
  local agent_id="$1"
  repo_cfg_value "agent-ports" "$agent_id"
}

agent_status_for_start_args() {
  local agent_id="$1"
  local start_args="$2"
  local state
  local label

  if [[ -z "$start_args" ]]; then
    printf '%s' "interactive"
    return
  fi

  if is_linux; then
    state="$(systemd_service_state "agent@${agent_id}")"
    case "$state" in
      active) printf '%s' "running" ;;
      inactive|failed|activating|deactivating) printf '%s' "$state" ;;
      *) printf '%s' "unavailable" ;;
    esac
    return
  fi

  if is_macos; then
    label="$(service_label_for_agent "$agent_id")"
    state="$(launchd_service_state "$label")"
    if [[ "$state" == "running" ]]; then
      printf '%s' "running"
    elif [[ -f "/Library/LaunchDaemons/${label}.plist" ]]; then
      printf '%s' "configured"
    else
      printf '%s' "unavailable"
    fi
    return
  fi

  printf '%s' "unknown"
}

prepare_agent_render_cache() {
  local agent_id
  local dir_name
  local kind
  local port
  local start_args
  local status
  local tui_args
  local tui_yolo_args

  RENDER_AGENT_IDS=()
  RENDER_AGENT_NAMES=()
  RENDER_AGENT_PORTS=()
  RENDER_AGENT_STATUSES=()
  RENDER_AGENT_TUI_ARGS=()
  RENDER_AGENT_TUI_YOLO_ARGS=()
  RENDER_AGENT_START_ARGS=()

  for agent_id in "$@"; do
    [[ -n "$agent_id" ]] || continue
    kind="$(known_agent_kind_for_id "$agent_id")" || continue
    dir_name="$(agent_directory_name "$agent_id")"
    port="$(agent_gateway_port "$agent_id")"
    load_agent_kind_definition "$kind"
    tui_args="${AELAB_AGENT_TUI_ARGS:-}"
    tui_yolo_args="${AELAB_AGENT_TUI_YOLO_ARGS:-}"
    start_args="${AELAB_AGENT_START_ARGS:-}"
    status="$(agent_status_for_start_args "$agent_id" "$start_args")"

    RENDER_AGENT_IDS+=("$agent_id")
    RENDER_AGENT_NAMES+=("$dir_name")
    RENDER_AGENT_PORTS+=("$port")
    RENDER_AGENT_STATUSES+=("$status")
    RENDER_AGENT_TUI_ARGS+=("$tui_args")
    RENDER_AGENT_TUI_YOLO_ARGS+=("$tui_yolo_args")
    RENDER_AGENT_START_ARGS+=("$start_args")
  done
}

render_agent_links_html() {
  local agent_id
  local dir_name
  local index
  local port
  local status
  local status_class
  local actions_html
  local details_html
  local title_html
  local tui_args
  local tui_url

  for index in "${!RENDER_AGENT_IDS[@]}"; do
    agent_id="${RENDER_AGENT_IDS[$index]}"
    dir_name="${RENDER_AGENT_NAMES[$index]}"
    port="${RENDER_AGENT_PORTS[$index]}"
    status="${RENDER_AGENT_STATUSES[$index]}"
    tui_args="${RENDER_AGENT_TUI_ARGS[$index]}"
    status_class="$(status_class_for_state "$status")"
    actions_html="$(render_action_menu_html "$agent_id")"
    if [[ -n "$tui_args" ]]; then
      tui_url="/tty/${agent_id}/tui/"
      title_html="<a href=\"$(html_escape "$tui_url")\" target=\"_blank\" rel=\"noreferrer\">$(html_escape "$dir_name")</a>"
    else
      title_html="<span class=\"item-name\">$(html_escape "$dir_name")</span>"
    fi
    details_html=""
    if [[ -n "$port" ]]; then
      details_html="<span class=\"detail-port\">port: <code>$(html_escape "$port")</code></span>"
    fi
    render_index_row_html "$title_html" "$status_class" "$status" "$details_html" "$actions_html"
  done
}

status_class_for_state() {
  local status="$1"

  if [[ "$status" == "running" || "$status" == "active" ]]; then
    printf 'status-running'
  elif [[ "$status" == "configured" || "$status" == "inactive" || "$status" == "activating" || "$status" == "deactivating" ]]; then
    printf 'status-configured'
  elif [[ "$status" == "interactive" ]]; then
    printf 'status-interactive'
  elif [[ "$status" == "unavailable" || "$status" == "failed" || "$status" == "unloaded" ]]; then
    printf 'status-unavailable'
  else
    printf 'status-unknown'
  fi
}

render_index_row_html() {
  local title_html="$1"
  local status_class="$2"
  local status="$3"
  local details_html="$4"
  local actions_html="$5"
  local status_html=""
  local actions_block=""

  if [[ -n "$status" ]]; then
    status_html=" <span class=\"$(html_escape "$status_class")\">$(html_escape "$status")</span>"
  fi
  if [[ -n "$actions_html" ]]; then
    actions_block="<div class=\"row-actions\">${actions_html}</div>"
  fi

  printf '        <li class="index-row"><div class="row-main"><div class="row-title">%s%s</div><div class="row-details">%s</div></div>%s</li>\n' \
    "$title_html" \
    "$status_html" \
    "$details_html" \
    "$actions_block"
}

render_service_links_html() {
  local service_id
  local route
  local route_port
  local route_html
  local service_id_html
  local status
  local status_class
  local title_html
  local details_html

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    status="$(service_status "$service_id")"
    status_class="$(status_class_for_state "$status")"
    case "$status" in
      running|active|interactive) ;;
      *) continue ;;
    esac
    route="$(expand_runtime_placeholders "${AELAB_SERVICE_CADDY_ROUTE:-}")"
    service_id_html="$(html_escape "$service_id")"
    if [[ "$route" == /* ]]; then
      route_html="$(html_escape "$route")"
      local managed_port_html=""
      if [[ -n "${AELAB_SERVICE_PORT:-}" ]]; then
        managed_port_html="<span class=\"detail-port\">port: <code>$(html_escape "$AELAB_SERVICE_PORT")</code></span>"
      fi
      title_html="<a href=\"$(html_escape "${route%/}/")\" target=\"_blank\" rel=\"noreferrer\">${service_id_html}</a>"
      details_html="${managed_port_html}${managed_port_html:+ }<span class=\"detail-path\">path: <code>${route_html}</code></span>"
      render_index_row_html "$title_html" "$status_class" "$status" "$details_html" ""
      continue
    fi
    if [[ "$route" == :* ]]; then
      route_port="${route#:}"
      route_html="$(html_escape "$route_port")"
      title_html="<span class=\"item-name\">${service_id_html}</span>"
      details_html="<span class=\"detail-port\">port: <code>${route_html}</code></span>"
      render_index_row_html "$title_html" "$status_class" "$status" "$details_html" ""
      continue
    fi
    if [[ -n "$route" ]]; then
      route_html="$(html_escape "$route")"
      title_html="<span class=\"item-name\">${service_id_html}</span>"
      details_html="<span>host: <code>${route_html}</code></span>"
      render_index_row_html "$title_html" "$status_class" "$status" "$details_html" ""
      continue
    fi
    title_html="<span class=\"item-name\">${service_id_html}</span>"
    render_index_row_html "$title_html" "$status_class" "$status" "" ""
  done < <(requested_service_ids_from_env)
}

render_action_menu_html() {
  local target="$1"
  local agent_id
  local agent_html=""
  local dir_name
  local index
  local interactive_agent_html=""
  local start_args
  local tui_args
  local option_url
  local shell_url
  local tool_html=""
  local sections_html=""
  local yolo_agent_html=""
  local tui_yolo_args
  local status

  shell_url="/tty/$(url_encode_path_segment "$target")/"
  tool_html+="            <a class=\"action-menu-item\" href=\"$(html_escape "$shell_url")\" target=\"_blank\" rel=\"noreferrer\">shell</a>"$'\n'

  for index in "${!RENDER_AGENT_IDS[@]}"; do
    agent_id="${RENDER_AGENT_IDS[$index]}"
    [[ -n "$agent_id" ]] || continue
    dir_name="${RENDER_AGENT_NAMES[$index]}"
    option_url="/tty/$(url_encode_path_segment "$target")/${agent_id}/tui/"
    tui_args="${RENDER_AGENT_TUI_ARGS[$index]}"
    [[ -n "$tui_args" ]] || continue
    start_args="${RENDER_AGENT_START_ARGS[$index]}"
    status="${RENDER_AGENT_STATUSES[$index]}"
    if [[ -z "$start_args" ]]; then
      interactive_agent_html+="            <a class=\"action-menu-item\" href=\"$(html_escape "$option_url")\" target=\"_blank\" rel=\"noreferrer\">$(html_escape "$dir_name")</a>"$'\n'
    elif [[ "$status" == "running" || "$status" == "active" ]]; then
      agent_html+="            <a class=\"action-menu-item\" href=\"$(html_escape "$option_url")\" target=\"_blank\" rel=\"noreferrer\">$(html_escape "$dir_name")</a>"$'\n'
    fi
    tui_yolo_args="${RENDER_AGENT_TUI_YOLO_ARGS[$index]}"
    if [[ -n "$tui_yolo_args" ]]; then
      option_url="/tty/$(url_encode_path_segment "$target")/${agent_id}/yolo/"
      yolo_agent_html+="            <a class=\"action-menu-item action-menu-item-yolo\" href=\"$(html_escape "$option_url")\" target=\"_blank\" rel=\"noreferrer\">$(html_escape "$dir_name")</a>"$'\n'
    fi
  done

  sections_html+="            <div class=\"action-menu-section\" data-open-with-section data-terminal-path=\"$(html_escape "$shell_url")\">"$'\n'
  sections_html+="              <div class=\"action-menu-heading\">open with</div>"$'\n'
  sections_html+="$tool_html"
  sections_html+="            </div>"$'\n'
  if [[ -n "$interactive_agent_html" ]]; then
    sections_html+="            <div class=\"action-menu-section\">"$'\n'
    sections_html+="              <div class=\"action-menu-heading\">interactive</div>"$'\n'
    sections_html+="$interactive_agent_html"
    sections_html+="            </div>"$'\n'
  fi
  if [[ -n "$yolo_agent_html" ]]; then
    sections_html+="            <div class=\"action-menu-section\">"$'\n'
    sections_html+="              <div class=\"action-menu-heading\">yolo</div>"$'\n'
    sections_html+="$yolo_agent_html"
    sections_html+="            </div>"$'\n'
  fi
  if [[ -n "$agent_html" ]]; then
    sections_html+="            <div class=\"action-menu-section\">"$'\n'
    sections_html+="              <div class=\"action-menu-heading\">running</div>"$'\n'
    sections_html+="$agent_html"
    sections_html+="            </div>"$'\n'
  fi
  cat <<EOF
<details class="action-menu">
          <summary class="icon-button row-action-button" aria-label="Actions" title="Actions">
            <svg class="icon-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M12 5v14"/><path d="M5 12h14"/></svg>
          </summary>
          <div class="action-menu-panel">
${sections_html}          </div>
        </details>
EOF
}

render_host_yolo_menu_section_js() {
  local agent_id
  local dir_name
  local index
  local option_url
  local yolo_agent_html=""
  local tui_yolo_args

  for index in "${!RENDER_AGENT_IDS[@]}"; do
    agent_id="${RENDER_AGENT_IDS[$index]}"
    [[ -n "$agent_id" ]] || continue
    tui_yolo_args="${RENDER_AGENT_TUI_YOLO_ARGS[$index]}"
    [[ -n "$tui_yolo_args" ]] || continue
    dir_name="${RENDER_AGENT_NAMES[$index]}"
    option_url="/tty/$(url_encode_path_segment "$agent_id")/yolo/"
    yolo_agent_html+="<a class=\"action-menu-item action-menu-item-yolo\" href=\"$(html_escape "$option_url")\" target=\"_blank\" rel=\"noreferrer\">$(html_escape "$dir_name")</a>"
  done

  [[ -n "$yolo_agent_html" ]] || return 0
  js_single_quote_escape "<div class=\"action-menu-section\"><div class=\"action-menu-heading\">yolo</div>${yolo_agent_html}</div>"
}

render_project_links_html() {
  local raw="${AELAB_PROJECTS:-}"
  local item
  local title
  local path
  local project_url
  local actions_html
  local title_html
  local details_html

  [[ -n "$raw" ]] || return 0

  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    [[ "$item" == *=* ]] || continue
    title="${item%%=*}"
    path="${item#*=}"
    [[ -n "$title" && -n "$path" ]] || continue
    project_url="/tty/$(url_encode_path_segment "$title")/"
    actions_html="$(render_action_menu_html "$title")"
    title_html="<a href=\"$(html_escape "$project_url")\" target=\"_blank\" rel=\"noreferrer\">$(html_escape "$title")</a>"
    details_html="<span class=\"detail-path\">path: <code>$(html_escape "$path")</code></span>"
    render_index_row_html "$title_html" "" "" "$details_html" "$actions_html"
  done
}

render_index_section_html() {
  local section_id="$1"
  local title="$2"
  local links_html="$3"

  [[ -n "$links_html" ]] || return 0
  cat <<EOF
    <section class="index-section" data-section="$(html_escape "$section_id")">
      <h2><button class="section-toggle" type="button" aria-expanded="true"><span class="section-caret">▾</span><span>$(html_escape "$title")</span></button></h2>
      <ul>
${links_html}
      </ul>
    </section>
EOF
}

service_status() {
  local service_id="$1"

  load_service_definition "$service_id"

  if is_linux; then
    systemd_service_state "$(service_systemd_name)"
    return
  fi

  if is_macos; then
    launchd_service_state "$(service_launchd_label)"
    return
  fi

  printf '%s' "unknown"
}

tailscale_only_enabled() {
  case "${AELAB_TAILSCALE_ONLY:-}" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

render_index_html() {
  local host_name
  local generated_at
  local generated_commit
  local agent_links_html
  local project_links_html
  local service_links_html
  local sections_html
  local host_yolo_menu_section_js
  local tailscale_nav_html
  local current_section
  local rendered

  host_name="$(display_host_name)"
  current_section="$(tailscale_section_name)"
  generated_at="$(TZ="$(display_timezone)" date +"%Y-%m-%d %H:%M:%S %Z")"
  generated_commit="$(render_commit_hash)"
  prepare_agent_render_cache "$@"
  agent_links_html="$(render_agent_links_html)"
  project_links_html="$(render_project_links_html)"
  service_links_html="$(render_service_links_html)"
  host_yolo_menu_section_js="$(render_host_yolo_menu_section_js)"
  sections_html="$(render_index_section_html "projects" "projects" "$project_links_html")"
  if [[ -n "$agent_links_html" ]]; then
    if [[ -n "$sections_html" ]]; then
      sections_html="${sections_html}"$'\n'"$(render_index_section_html "agents" "agents" "$agent_links_html")"
    else
      sections_html="$(render_index_section_html "agents" "agents" "$agent_links_html")"
    fi
  fi
  if [[ -n "$service_links_html" ]]; then
    if [[ -n "$sections_html" ]]; then
      sections_html="${sections_html}"$'\n'"$(render_index_section_html "services" "services" "$service_links_html")"
    else
      sections_html="$(render_index_section_html "services" "services" "$service_links_html")"
    fi
  fi
  tailscale_nav_html="$(render_tailscale_nav_html "$current_section")"
  rendered="$(mktemp)"

  render_template "$(index_template_path)" "$rendered" \
    __PAGE_TITLE__ "$(aelab_name) on $(html_escape "$host_name")" \
    __HOST_NAME__ "$(html_escape "$host_name")" \
    __TAILSCALE_NAV_HTML__ "$tailscale_nav_html" \
    __AGENT_LINKS_HTML__ "$sections_html" \
    __HOST_YOLO_MENU_SECTION_JS__ "$host_yolo_menu_section_js" \
    __GENERATED_AT__ "$generated_at" \
    __GENERATED_COMMIT__ "$(html_escape "$generated_commit")"
  cat "$rendered"
  rm -f "$rendered"
}

render_managed_handlers() {
  local agent_id
  local port
  local service_id
  local route
  local upstream
  local root_route_upstream=""

  if tailscale_only_enabled; then
    cat <<EOF
  @tailscale remote_ip 100.64.0.0/10 fd7a:115c:a1e0::/48 127.0.0.1 ::1

  handle @tailscale {
EOF
  fi

  for agent_id in "$@"; do
    port="$(agent_gateway_port "$agent_id")"
    [[ -n "$port" ]] || continue
    cat <<EOF
    @agent_${agent_id} path /${agent_id} /${agent_id}/*
    handle @agent_${agent_id} {
      uri strip_prefix /${agent_id}
      reverse_proxy 127.0.0.1:${port}
    }
EOF
  done

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    route="$(expand_runtime_placeholders "${AELAB_SERVICE_CADDY_ROUTE:-}")"
    upstream="$(expand_runtime_placeholders "${AELAB_SERVICE_CADDY_UPSTREAM:-}")"
    [[ "$route" == /* && -n "$upstream" ]] || continue
    if [[ "$route" == "/" ]]; then
      root_route_upstream="$upstream"
      continue
    fi
    cat <<EOF
    @service_${service_id} path ${route} ${route}/*
    handle @service_${service_id} {
      reverse_proxy ${upstream}
    }
EOF
  done < <(requested_service_ids_from_env)

  if [[ -n "$root_route_upstream" ]]; then
    cat <<EOF
    handle {
      reverse_proxy ${root_route_upstream}
    }
EOF
  fi

  if tailscale_only_enabled; then
    cat <<EOF
    root * "$(generated_web_root_relative)"
    file_server
  }

  respond "forbidden" 403
EOF
  else
    cat <<EOF
  root * "$(generated_web_root_relative)"
  file_server
EOF
  fi
}

render_service_site_blocks() {
  local service_id
  local route
  local site_address
  local upstream

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    route="$(expand_runtime_placeholders "${AELAB_SERVICE_CADDY_ROUTE:-}")"
    upstream="$(expand_runtime_placeholders "${AELAB_SERVICE_CADDY_UPSTREAM:-}")"
    [[ -n "$route" && "$route" != /* && -n "$upstream" ]] || continue
    site_address="$route"
    if [[ "$site_address" != :* && "$site_address" != *:* ]]; then
      site_address="${site_address}:80"
    fi
    if tailscale_only_enabled; then
      cat <<EOF
${site_address} {
  @tailscale remote_ip 100.64.0.0/10 fd7a:115c:a1e0::/48 127.0.0.1 ::1

  handle @tailscale {
    reverse_proxy ${upstream}
  }

  respond "forbidden" 403
}

EOF
    else
      cat <<EOF
${site_address} {
  reverse_proxy ${upstream}
}

EOF
    fi
  done < <(requested_service_ids_from_env)
}

render_managed_block() {
  local tls_mode
  local site_host

  render_service_site_blocks

  tls_mode="$(caddy_tls_mode)"
  if [[ "$tls_mode" == "internal" ]]; then
    site_host="$(caddy_site_host)"
    if [[ -z "$site_host" ]]; then
      echo "AELAB_CADDY_TLS=internal needs AELAB_HOST in [hosts]" >&2
      return 1
    fi
    cat <<EOF
http://${site_host} {
  redir https://${site_host}{uri}
}

https://${site_host} {
  tls internal {
    curves x25519 secp256r1 secp384r1
  }
$(render_managed_handlers "$@")
}
EOF
    return 0
  fi

  cat <<EOF
:80 {
$(render_managed_handlers "$@")
}
EOF
}

write_index_html() {
  local tmp_file
  tmp_file="$(mktemp)"
  mkdir -p "$(generated_web_root)"
  render_index_html "$@" > "$tmp_file"
  overwrite_file_preserving_metadata "$tmp_file" "$(generated_index_path)"
}

write_caddyfile() {
  local tmp_file
  tmp_file="$(mktemp)"
  mkdir -p "$(dirname "$(caddyfile_path)")"
  cat <<EOF > "$tmp_file"
# Generated by infra/commands/render.sh caddy. Do not edit manually.
# $(aelab_name) owns this root Caddyfile and imports:
# - optional host-local site configs under $(aelab_caddy_import_dir)/*.caddy

import $(aelab_caddy_import_dir)/*.caddy

# BEGIN AELAB MANAGED
$(render_managed_block "$@")
# END AELAB MANAGED
EOF
  overwrite_file_preserving_metadata "$tmp_file" "$(caddyfile_path)"
  if command -v caddy >/dev/null 2>&1; then
    caddy fmt --overwrite "$(caddyfile_path)" >/dev/null 2>&1 || true
  fi
}

render_brew_target() {
  local package_count
  BREW_TAPS=()
  BREW_PACKAGES=()
  BREW_CASKS=()

  collect_service_packages
  collect_agent_packages
  mkdir -p "$(dirname "$(brewfile_path)")"
  render_brewfile > "$(brewfile_path)"
  package_count=0
  if [[ -n "${BREW_PACKAGES[*]-}" ]]; then
    package_count="${#BREW_PACKAGES[@]}"
  fi
  log "rendered $(brewfile_path) (${package_count} packages)"
  log --verbose "[rendered] $(brewfile_path) with ${package_count} packages"
}

collect_render_gateway_agent_ids() {
  local -a requested_agents=()
  local agent_id
  local kind
  local port

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    known_agent_kind_for_id "$agent_id" >/dev/null || continue
    agent_is_managed "$agent_id" || continue
    port="$(agent_gateway_port "$agent_id")"
    if [[ -z "$port" ]]; then
      echo "missing port for agent ${agent_id} in $(repo_cfg_file)" >&2
      exit 1
    fi
    requested_agents+=("$agent_id")
  done < <(requested_agent_ids_from_env)

  ((${#requested_agents[@]} == 0)) || printf '%s\n' "${requested_agents[@]}"
}

collect_render_agent_ids() {
  local agent_id

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    printf '%s\n' "$agent_id"
  done < <(requested_agent_ids_from_env)
}

render_index_target() {
  local -a requested_agents=()
  local agent_id

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    requested_agents+=("$agent_id")
  done < <(collect_render_agent_ids)

  write_index_html "${requested_agents[@]+"${requested_agents[@]}"}"
  log "rendered $(generated_index_path)"
  log --verbose "[rendered] $(generated_index_path) from $(index_template_path)"
}

render_caddy_target() {
  local -a requested_agents=()
  local agent_id
  local route_count=0

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    requested_agents+=("$agent_id")
  done < <(collect_render_gateway_agent_ids)

  render_index_target >/dev/null
  write_caddyfile "${requested_agents[@]+"${requested_agents[@]}"}"
  if [[ -n "${requested_agents[*]-}" ]]; then
    route_count="${#requested_agents[@]}"
  fi
  log "rendered $(caddyfile_path) (${route_count} agent routes)"
  log --verbose "[rendered] $(caddyfile_path) with ${route_count} agent routes"
}

usage() {
  cat <<EOF
Usage:
  $(basename "$0") [all|brew|caddy|front]
EOF
}

main() {
  local target="${1:-all}"

  case "$target" in
    all)
      render_brew_target
      render_caddy_target
      ;;
    brew)
      render_brew_target
      ;;
    caddy)
      render_caddy_target
      ;;
    front)
      render_index_target
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      echo "unknown render target: $target" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
