#!/usr/bin/env bash
set -euo pipefail

# shellcheck disable=SC1091
source "$(cd "$(dirname "$0")/.." && pwd)/commands/core.sh"

load_host_env

CLAWLAB_ROOT="${CLAWLAB_ROOT:-$(clawlab_root)}"

brewfile_path() {
  printf '%s/infra/generated/Brewfile' "$(repo_root)"
}

caddyfile_path() {
  printf '%s/infra/generated/Caddyfile' "$(repo_root)"
}

dash_page_template_path() {
  printf '%s/infra/templates/dash-page.html' "$(repo_root)"
}

generated_web_root() {
  printf '%s/infra/generated/caddy' "$(repo_root)"
}

generated_web_root_relative() {
  printf '%s' "./generated/caddy"
}

generated_index_path() {
  printf '%s/index.html' "$(generated_web_root)"
}

append_unique() {
  local value="$1"
  local existing

  [[ -n "$value" ]] || return 0

  for existing in "${BREW_PACKAGES[@]:-}"; do
    [[ "$existing" != "$value" ]] || return 0
  done

  BREW_PACKAGES+=("$value")
}

append_unique_tap() {
  local value="$1"
  local existing

  [[ -n "$value" ]] || return 0

  for existing in "${BREW_TAPS[@]:-}"; do
    [[ "$existing" != "$value" ]] || return 0
  done

  BREW_TAPS+=("$value")
}

append_unique_cask() {
  local value="$1"
  local existing

  [[ -n "$value" ]] || return 0

  for existing in "${BREW_CASKS[@]:-}"; do
    [[ "$existing" != "$value" ]] || return 0
  done

  BREW_CASKS+=("$value")
}

append_list() {
  local raw="$1"
  local item

  raw="$(trim_commas "$raw")"
  [[ -n "$raw" ]] || return 0
  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    append_unique "$item"
  done
}

append_tap_list() {
  local raw="$1"
  local item

  raw="$(trim_commas "$raw")"
  [[ -n "$raw" ]] || return 0
  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    append_unique_tap "$item"
  done
}

append_cask_list() {
  local raw="$1"
  local item

  raw="$(trim_commas "$raw")"
  [[ -n "$raw" ]] || return 0
  # shellcheck disable=SC2206
  local -a items=($raw)
  for item in "${items[@]}"; do
    append_unique_cask "$item"
  done
}

collect_service_packages() {
  local service_id
  local packages
  local casks

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    case "${CLAWLAB_SERVICE_INSTALL_OPTIONAL:-}" in
      1|true|yes|on)
        continue
        ;;
    esac
    append_tap_list "${CLAWLAB_SERVICE_BREW_TAPS:-}"
    packages="${CLAWLAB_SERVICE_BREW_PACKAGES:-}"
    casks="${CLAWLAB_SERVICE_BREW_CASKS:-}"
    if is_macos && is_arm64; then
      packages="${CLAWLAB_SERVICE_BREW_PACKAGES_MACOS_ARM64:-$packages}"
      casks="${CLAWLAB_SERVICE_BREW_CASKS_MACOS_ARM64:-$casks}"
    fi
    append_list "$packages"
    append_cask_list "$casks"
  done < <(requested_service_ids_from_env)
}

collect_agent_packages() {
  local agent_id
  local kind

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    kind="$(agent_kind_for_id "$agent_id")"
    load_agent_kind_definition "$kind"
    append_tap_list "${CLAWLAB_AGENT_BREW_TAPS:-}"
    append_list "${CLAWLAB_AGENT_BREW_PACKAGES:-}"
  done < <(requested_agent_ids_from_env)
}

render_brewfile() {
  local tap
  local pkg
  local cask

  printf '# Generated by infra/commands/render.sh brew. Do not edit manually.\n'
  printf '# Based on config/custom/host/.env, config/custom/repo.ini, config/agents/*.env, config/custom/override/agents/*.env, config/services/*.env, and config/custom/override/services/*.env.\n'
  printf '\n'

  if [[ "${#BREW_TAPS[@]}" -gt 0 ]]; then
    for tap in "${BREW_TAPS[@]}"; do
      printf 'tap "%s"\n' "$tap"
    done
    printf '\n'
  fi

  for pkg in "${BREW_PACKAGES[@]}"; do
    printf 'brew "%s"\n' "$pkg"
  done

  if [[ "${#BREW_CASKS[@]}" -gt 0 ]]; then
    printf '\n'
    for cask in "${BREW_CASKS[@]}"; do
      printf 'cask "%s"\n' "$cask"
    done
  fi
}

overwrite_file_preserving_metadata() {
  local src="$1"
  local dest="$2"

  if [[ -e "$dest" ]]; then
    cat "$src" > "$dest"
    rm -f "$src"
  else
    mv "$src" "$dest"
  fi
}

lowercase() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

display_timezone() {
  printf '%s' "${CLAWLAB_DISPLAY_TIMEZONE:-Europe/Belgrade}"
}

normalize_host_alias() {
  local item="$1"
  item="${item#http://}"
  item="${item#https://}"
  item="${item%%/*}"
  item="${item%%.*}"
  item="$(lowercase "$item")"

  case "$item" in
    agents) printf '%s' "agent-server" ;;
    apps) printf '%s' "app-server" ;;
    data) printf '%s' "data-server" ;;
    *) printf '%s' "$item" ;;
  esac
}

tailscale_section_name() {
  local selected
  selected="${CLAWLAB_HOST:-${TAILSCALE_DNS_NAME:-$(hostname -s 2>/dev/null || hostname)}}"
  normalize_host_alias "$selected"
}

tailscale_nav_entries() {
  repo_cfg_entries "hosts"
}

html_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  printf '%s' "$value"
}

render_tailscale_nav_html() {
  local current="$1"
  local alias
  local url
  local class_name
  local label

  while IFS=$'\t' read -r alias url; do
    [[ -n "$alias" && -n "$url" ]] || continue
    class_name="segmented-link"
    label="$(normalize_host_alias "$alias")"
    if [[ "$label" == "$current" ]]; then
      class_name="segmented-link is-active tint-trigger"
      printf '        <label class="%s" title="Change tint for this host">\n' \
        "$(html_escape "$class_name")"
      printf '          <span class="segment-label">%s</span>\n' \
        "$(html_escape "$label")"
      printf '          <input class="segment-tint-picker" id="active-tint-picker" type="color" value="#0f766e" aria-label="Choose accent tint for this host">\n'
      printf '        </label>\n'
      continue
    fi
    printf '        <a class="%s" href="%s">%s</a>\n' \
      "$(html_escape "$class_name")" \
      "$(html_escape "$url")" \
      "$(html_escape "$label")"
  done < <(tailscale_nav_entries)
}

agent_gateway_port() {
  local agent_id="$1"
  repo_cfg_value "agent-ports" "$agent_id"
}

agent_status() {
  local agent_id="$1"
  local state
  local label

  if is_linux; then
    state="$(systemd_service_state "agent@${agent_id}")"
    case "$state" in
      active) printf '%s' "running" ;;
      inactive|failed|activating|deactivating) printf '%s' "$state" ;;
      *) printf '%s' "unavailable" ;;
    esac
    return
  fi

  if is_macos; then
    label="$(service_label_for_agent "$agent_id")"
    state="$(launchd_service_state "$label")"
    if [[ "$state" == "running" ]]; then
      printf '%s' "running"
    elif [[ -f "/Library/LaunchDaemons/${label}.plist" ]]; then
      printf '%s' "configured"
    else
      printf '%s' "unavailable"
    fi
    return
  fi

  printf '%s' "unknown"
}

render_agent_links_html() {
  local -a ids=("$@")
  local agent_id
  local dir_name
  local port
  local status
  local status_class
  local agent_path

  for agent_id in "${ids[@]}"; do
    dir_name="$(agent_directory_name "$agent_id")"
    port="$(agent_gateway_port "$agent_id")"
    status="$(agent_status "$agent_id")"
    agent_path="/${agent_id}/"
    status_class="$(status_class_for_state "$status")"
    if [[ "$dir_name" == *"-picoclaw" ]]; then
      agent_path="/${agent_id}/health"
    elif [[ "$dir_name" == *"-openclaw" ]]; then
      agent_path="/${agent_id}/overview"
    fi
    [[ -n "$port" ]] || continue
    printf '        <li><a href="%s" target="_blank" rel="noreferrer">%s</a> <small><span class="%s">%s</span> <span>port: <code>%s</code></span></small></li>\n' \
      "$(html_escape "$agent_path")" \
      "$(html_escape "$dir_name")" \
      "$(html_escape "$status_class")" \
      "$(html_escape "$status")" \
      "$(html_escape "$port")"
  done
}

status_class_for_state() {
  local status="$1"

  if [[ "$status" == "running" || "$status" == "active" ]]; then
    printf 'status-running'
  elif [[ "$status" == "configured" || "$status" == "inactive" || "$status" == "activating" || "$status" == "deactivating" ]]; then
    printf 'status-configured'
  elif [[ "$status" == "unavailable" || "$status" == "failed" || "$status" == "unloaded" ]]; then
    printf 'status-unavailable'
  else
    printf 'status-unknown'
  fi
}

render_service_links_html() {
  local service_id
  local route
  local route_port
  local route_html
  local service_id_html
  local status
  local status_class
  local status_class_html
  local status_html
  local host_name
  local host_name_html
  local managed_id
  local managed_root_id
  local managed_status
  local managed_status_class

  managed_root_id="$(caddy_root_service_id)"

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    if [[ -n "$managed_root_id" && "$service_id" == "$managed_root_id" ]]; then
      if service_requested_from_env "caddy"; then
        continue
      fi
    fi
    load_service_definition "$service_id"
    status="$(service_status "$service_id")"
    status_class="$(status_class_for_state "$status")"
    route="$(expand_runtime_placeholders "${CLAWLAB_SERVICE_CADDY_ROUTE:-}")"
    service_id_html="$(html_escape "$service_id")"
    status_class_html="$(html_escape "$status_class")"
    status_html="$(html_escape "$status")"
    if [[ "$route" == /* ]]; then
      route_html="$(html_escape "$route")"
      printf '        <li><a href="%s/" target="_blank" rel="noreferrer">%s</a> <small><span class="%s">%s</span> <span>path: <code>%s</code></span></small></li>\n' \
        "$route_html" \
        "$service_id_html" \
        "$status_class_html" \
        "$status_html" \
        "$route_html"
      continue
    fi
    if [[ "$route" == :* ]]; then
      route_port="${route#:}"
      route_html="$(html_escape "$route_port")"
      host_name="${CLAWLAB_HOST:-$(hostname -s 2>/dev/null || hostname)}"
      host_name_html="$(html_escape "$host_name")"
      printf '        <li><a href="http://%s:%s/" target="_blank" rel="noreferrer">%s</a> <small><span class="%s">%s</span> <span>port: <code>%s</code></span></small></li>\n' \
        "$host_name_html" \
        "$route_html" \
        "$service_id_html" \
        "$status_class_html" \
        "$status_html" \
        "$route_html"
      continue
    fi
    if [[ -n "$route" ]]; then
      route_html="$(html_escape "$route")"
      printf '        <li><a href="http://%s/" target="_blank" rel="noreferrer">%s</a> <small><span class="%s">%s</span> <span>host: <code>%s</code></span></small></li>\n' \
        "$route_html" \
        "$service_id_html" \
        "$status_class_html" \
        "$status_html" \
        "$route_html"
      continue
    fi
    printf '        <li><span class="item-name">%s</span> <small><span class="%s">%s</span></small></li>\n' \
      "$service_id_html" \
      "$status_class_html" \
      "$status_html"
    if [[ "$service_id" == "caddy" ]]; then
      while IFS= read -r managed_id; do
        [[ -n "$managed_id" ]] || continue
        load_service_definition "$managed_id"
        managed_status="$(service_status "$managed_id")"
        managed_status_class="$(status_class_for_state "$managed_status")"
        host_name="${CLAWLAB_HOST:-$(hostname -s 2>/dev/null || hostname)}"
        local managed_port_html=""
        if [[ -n "${CLAWLAB_SERVICE_PORT:-}" ]]; then
          managed_port_html=" <span>port: <code>$(html_escape "$CLAWLAB_SERVICE_PORT")</code></span>"
        fi
        printf '        <li><a href="http://%s/">%s</a> <small><span class="%s">%s</span>%s</small></li>\n' \
          "$(html_escape "$host_name")" \
          "$(html_escape "$managed_id")" \
          "$(html_escape "$managed_status_class")" \
          "$(html_escape "$managed_status")" \
          "$managed_port_html"
      done < <(caddy_managed_service_ids)
    fi
  done < <(requested_service_ids_from_env)
}

render_dash_section_html() {
  local section_id="$1"
  local title="$2"
  local links_html="$3"

  [[ -n "$links_html" ]] || return 0
  cat <<EOF
    <section class="dashboard-section" data-section="$(html_escape "$section_id")">
      <h2><button class="section-toggle" type="button" aria-expanded="true"><span class="section-caret">▾</span><span>$(html_escape "$title")</span></button></h2>
      <ul>
${links_html}
      </ul>
    </section>
EOF
}

service_status() {
  local service_id="$1"

  load_service_definition "$service_id"

  if is_linux; then
    systemd_service_state "$(service_systemd_name)"
    return
  fi

  if is_macos; then
    launchd_service_state "$(service_launchd_label)"
    return
  fi

  printf '%s' "unknown"
}

caddy_root_upstream() {
  local service_id
  local state

  if ! service_requested_from_env "caddy"; then
    return 0
  fi

  service_id="$(caddy_root_service_id)"
  [[ -n "$service_id" ]] || return 0

  state="$(service_status "$service_id")"
  if [[ "$state" == "active" || "$state" == "running" ]]; then
    load_service_definition "$service_id"
    printf '%s' "$(expand_runtime_placeholders "$CLAWLAB_SERVICE_CADDY_ROOT_UPSTREAM")"
  fi
}

render_index_html() {
  local host_name
  local generated_at
  local agent_links_html
  local service_links_html
  local sections_html
  local tailscale_nav_html
  local current_section
  local rendered
  local -a ids=("$@")

  host_name="$(hostname -s 2>/dev/null || hostname)"
  current_section="$(tailscale_section_name)"
  generated_at="$(TZ="$(display_timezone)" date +"%Y-%m-%d %H:%M:%S %Z")"
  agent_links_html="$(render_agent_links_html "${ids[@]}")"
  service_links_html="$(render_service_links_html)"
  sections_html="$(render_dash_section_html "agents" "agents" "$agent_links_html")"
  if [[ -n "$service_links_html" ]]; then
    if [[ -n "$sections_html" ]]; then
      sections_html="${sections_html}"$'\n'"$(render_dash_section_html "services" "services" "$service_links_html")"
    else
      sections_html="$(render_dash_section_html "services" "services" "$service_links_html")"
    fi
  fi
  tailscale_nav_html="$(render_tailscale_nav_html "$current_section")"
  rendered="$(mktemp)"

  render_template "$(dash_page_template_path)" "$rendered" \
    __PAGE_TITLE__ "clawlab on $(html_escape "$host_name")" \
    __HOST_NAME__ "$(html_escape "$host_name")" \
    __TAILSCALE_NAV_HTML__ "$tailscale_nav_html" \
    __AGENT_LINKS_HTML__ "$sections_html" \
    __GENERATED_AT__ "$generated_at"
  cat "$rendered"
  rm -f "$rendered"
}

render_managed_block() {
  local agent_id
  local port
  local service_id
  local route
  local site_address
  local upstream
  local root_upstream

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    route="$(expand_runtime_placeholders "${CLAWLAB_SERVICE_CADDY_ROUTE:-}")"
    upstream="${CLAWLAB_SERVICE_CADDY_UPSTREAM:-}"
    [[ -n "$route" && "$route" != /* && -n "$upstream" ]] || continue
    site_address="$route"
    if [[ "$site_address" != :* && "$site_address" != *:* ]]; then
      site_address="${site_address}:80"
    fi
    cat <<EOF
${site_address} {
  @tailscale remote_ip 100.64.0.0/10

  handle @tailscale {
    reverse_proxy ${upstream}
  }

  respond "forbidden" 403
}

EOF
  done < <(requested_service_ids_from_env)

  cat <<EOF
:80 {
  @tailscale remote_ip 100.64.0.0/10

  handle @tailscale {
EOF

  for agent_id in "$@"; do
    port="$(agent_gateway_port "$agent_id")"
    [[ -n "$port" ]] || continue
    cat <<EOF
    @agent_${agent_id} path /${agent_id} /${agent_id}/*
    handle @agent_${agent_id} {
      uri strip_prefix /${agent_id}
      reverse_proxy 127.0.0.1:${port}
    }
EOF
  done

  while IFS= read -r service_id; do
    [[ -n "$service_id" ]] || continue
    load_service_definition "$service_id"
    route="$(expand_runtime_placeholders "${CLAWLAB_SERVICE_CADDY_ROUTE:-}")"
    upstream="${CLAWLAB_SERVICE_CADDY_UPSTREAM:-}"
    [[ "$route" == /* && -n "$upstream" ]] || continue
    cat <<EOF
    @service_${service_id} path ${route} ${route}/*
    handle @service_${service_id} {
      uri strip_prefix ${route}
      reverse_proxy ${upstream}
    }
EOF
  done < <(requested_service_ids_from_env)

  root_upstream="$(caddy_root_upstream)"

  if [[ -n "$root_upstream" ]]; then
    cat <<EOF
    handle {
      reverse_proxy ${root_upstream}
    }
  }

  respond "forbidden" 403
}
EOF
    return
  fi

  cat <<EOF
    root * "$(generated_web_root_relative)"
    file_server
  }

  respond "forbidden" 403
}
EOF
}

write_index_html() {
  local tmp_file
  tmp_file="$(mktemp)"
  mkdir -p "$(generated_web_root)"
  render_index_html "$@" > "$tmp_file"
  overwrite_file_preserving_metadata "$tmp_file" "$(generated_index_path)"
}

write_caddyfile() {
  local tmp_file
  tmp_file="$(mktemp)"
  mkdir -p "$(dirname "$(caddyfile_path)")"
  cat <<EOF > "$tmp_file"
# Generated by infra/commands/render.sh caddy. Do not edit manually.
# Clawlab owns this root Caddyfile and imports:
# - optional host-local site configs under /etc/clawlab/*.caddy

import /etc/clawlab/*.caddy

# BEGIN CLAWLAB MANAGED
$(render_managed_block "$@")
# END CLAWLAB MANAGED
EOF
  overwrite_file_preserving_metadata "$tmp_file" "$(caddyfile_path)"
  if command -v caddy >/dev/null 2>&1; then
    caddy fmt --overwrite "$(caddyfile_path)" >/dev/null 2>&1 || true
  fi
}

render_brew_target() {
  BREW_TAPS=()
  BREW_PACKAGES=()
  BREW_CASKS=()

  collect_service_packages
  collect_agent_packages
  mkdir -p "$(dirname "$(brewfile_path)")"
  render_brewfile > "$(brewfile_path)"
  printf '[rendered] %s with %s packages\n' "$(brewfile_path)" "${#BREW_PACKAGES[@]}"
}

collect_render_agent_ids() {
  local -a requested_agents=()
  local agent_id
  local port

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    port="$(agent_gateway_port "$agent_id")"
    if [[ -z "$port" ]]; then
      echo "missing port for agent ${agent_id} in $(repo_cfg_file)" >&2
      exit 1
    fi
    requested_agents+=("$agent_id")
  done < <(requested_agent_ids_from_env)

  printf '%s\n' "${requested_agents[@]}"
}

render_dash_target() {
  local -a requested_agents=()
  local agent_id

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    requested_agents+=("$agent_id")
  done < <(collect_render_agent_ids)

  write_index_html "${requested_agents[@]}"
  printf '[rendered] %s from %s\n' "$(generated_index_path)" "$(dash_page_template_path)"
}

render_caddy_target() {
  local -a requested_agents=()
  local agent_id

  while IFS= read -r agent_id; do
    [[ -n "$agent_id" ]] || continue
    requested_agents+=("$agent_id")
  done < <(collect_render_agent_ids)

  render_dash_target >/dev/null
  write_caddyfile "${requested_agents[@]}"
  printf '[rendered] %s with %s agent routes\n' "$(caddyfile_path)" "${#requested_agents[@]}"
}

usage() {
  cat <<EOF
Usage:
  $(basename "$0") [all|brew|caddy]
EOF
}

main() {
  local target="${1:-all}"

  case "$target" in
    all)
      render_brew_target
      render_caddy_target
      ;;
    brew)
      render_brew_target
      ;;
    caddy)
      render_caddy_target
      ;;
    dash)
      render_dash_target
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      echo "unknown render target: $target" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
